// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "../../lib/forge-std/src/Test.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import {RentDistributor} from "../../src/core/RentDistributor.sol";
import {PropertyRegistry} from "../../src/core/PropertyRegistry.sol";
import {MockERC20} from "../helpers/MockERC20.sol";
import {MockVotesToken} from "../helpers/MockVotesToken.sol";

/// @title MerkleAllocationTest
/// @notice Cross-validates the front-end allocator against the on-chain verifier.
///
///         `frontend/lib/merkle/{allocate,tree}.ts` decides what every investor can
///         claim, but RentDistributor independently re-derives the leaf, checks the
///         proof, AND caps the claim at the holder's snapshot entitlement. If the
///         two ever disagree the failure mode is silent in the UI and only shows up
///         as a reverting claim, so the agreement is pinned here.
///
///         The fixture is generated by:
///           cd frontend && npx tsx scripts/gen-merkle-fixture.ts
///         Regenerate it whenever the allocator or the leaf format changes.
contract MerkleAllocationTest is Test {
    struct Claim {
        uint256 amount;
        address investor;
        bytes32[] proof;
    }

    address internal constant ADMIN = address(0xA11);

    RentDistributor internal distributor;
    PropertyRegistry internal registry;
    MockERC20 internal usdc;
    MockVotesToken internal propToken;

    uint256 internal propertyId;
    uint256 internal snapshotBlock;

    // Fixture contents
    bytes32 internal merkleRoot;
    uint256 internal totalRent;
    uint256 internal allocated;
    uint256 internal unallocated;
    address internal escrow;
    Claim[] internal claims;

    function setUp() public {
        string memory raw = vm.readFile("test/fixtures/merkle-allocation.json");

        merkleRoot = vm.parseJsonBytes32(raw, ".merkleRoot");
        totalRent = vm.parseJsonUint(raw, ".totalRent");
        allocated = vm.parseJsonUint(raw, ".allocated");
        unallocated = vm.parseJsonUint(raw, ".unallocated");
        escrow = vm.parseJsonAddress(raw, ".escrow");

        vm.startPrank(ADMIN);

        PropertyRegistry registryImpl = new PropertyRegistry();
        registry = PropertyRegistry(
            address(new ERC1967Proxy(address(registryImpl), abi.encodeCall(PropertyRegistry.initialize, (ADMIN))))
        );

        usdc = new MockERC20("Mock USDC", "USDC");

        RentDistributor distImpl = new RentDistributor();
        distributor = RentDistributor(
            address(
                new ERC1967Proxy(
                    address(distImpl),
                    abi.encodeCall(RentDistributor.initialize, (ADMIN, address(registry), address(usdc)))
                )
            )
        );

        propertyId = registry.registerProperty("ipfs://QmFixture", 1_000 ether, 1e18, address(0), bytes32(0), 0);

        propToken = new MockVotesToken("PropToken", "PT");
        registry.setTokenAddress(propertyId, address(propToken));

        usdc.mint(ADMIN, totalRent);
        usdc.approve(address(distributor), type(uint256).max);

        vm.stopPrank();

        // Mint exactly the holdings the fixture was computed from, so the on-chain
        // entitlement cap is evaluated against the same numbers the allocator used.
        address[] memory holderAddrs = vm.parseJsonAddressArray(raw, ".holderAddresses");
        uint256[] memory holderVotes = vm.parseJsonUintArray(raw, ".holderVotes");
        assertEq(holderAddrs.length, holderVotes.length, "fixture holder arrays disagree");

        for (uint256 i = 0; i < holderAddrs.length; i++) {
            vm.prank(ADMIN);
            propToken.mint(holderAddrs[i], holderVotes[i]);
            // PropertyToken self-delegates on receipt; the mock needs it done explicitly.
            vm.prank(holderAddrs[i]);
            propToken.delegate(holderAddrs[i]);
        }

        // Decode the claim table. Each entry is stored separately because Solidity
        // cannot decode an array of structs holding dynamic arrays in one go.
        address[] memory investors = vm.parseJsonAddressArray(raw, ".claimInvestors");
        uint256[] memory amounts = vm.parseJsonUintArray(raw, ".claimAmounts");
        for (uint256 i = 0; i < investors.length; i++) {
            bytes32[] memory proof = vm.parseJsonBytes32Array(raw, string.concat(".claimProofs[", vm.toString(i), "]"));
            claims.push(Claim({investor: investors[i], amount: amounts[i], proof: proof}));
        }

        vm.roll(block.number + 1);
        snapshotBlock = block.number - 1;
    }

    function _deposit() internal returns (uint256 periodId) {
        vm.prank(ADMIN);
        periodId = distributor.depositRent(propertyId, totalRent, merkleRoot, snapshotBlock);
    }

    // ─── Cross-validation ────────────────────────────────────────────────────

    function test_fixture_isNonTrivial() public view {
        assertGt(claims.length, 1, "fixture must cover several holders");
        assertGt(unallocated, 0, "fixture must exercise the excluded-escrow path");
    }

    /// @dev The whole point: every proof the TypeScript tree produced must satisfy
    ///      MerkleProof.verify AND land inside the on-chain entitlement cap.
    function test_everyGeneratedProofClaimsSuccessfully() public {
        uint256 periodId = _deposit();

        for (uint256 i = 0; i < claims.length; i++) {
            Claim memory c = claims[i];
            uint256 before = usdc.balanceOf(c.investor);

            vm.prank(c.investor);
            distributor.claimRent(propertyId, periodId, c.amount, c.proof);

            assertEq(usdc.balanceOf(c.investor), before + c.amount, "claim paid the wrong amount");
            assertTrue(distributor.hasClaimed(propertyId, periodId, c.investor));
        }
    }

    function test_totalClaimedMatchesAllocated() public {
        uint256 periodId = _deposit();

        for (uint256 i = 0; i < claims.length; i++) {
            vm.prank(claims[i].investor);
            distributor.claimRent(propertyId, periodId, claims[i].amount, claims[i].proof);
        }

        assertEq(distributor.getRentPeriod(propertyId, periodId).totalClaimed, allocated);
    }

    /// @dev The excluded escrow's share must stay in the contract rather than being
    ///      quietly handed to someone else — that is what makes it reclaimable later.
    function test_escrowShareStaysUnclaimed() public {
        uint256 periodId = _deposit();

        for (uint256 i = 0; i < claims.length; i++) {
            vm.prank(claims[i].investor);
            distributor.claimRent(propertyId, periodId, claims[i].amount, claims[i].proof);
            assertTrue(claims[i].investor != escrow, "escrow must not receive a leaf");
        }

        assertEq(usdc.balanceOf(address(distributor)), unallocated);
        assertEq(totalRent - allocated, unallocated);
    }

    /// @dev Guards the largest-remainder rounding: one extra wei on any allocation
    ///      must breach the ceil() cap rather than being absorbed silently.
    function test_revert_claimingOneWeiMoreThanAllocated() public {
        uint256 periodId = _deposit();

        Claim memory c = claims[0];
        vm.prank(c.investor);
        vm.expectRevert();
        distributor.claimRent(propertyId, periodId, c.amount + 1, c.proof);
    }
}
